meta_product_name: "Tem Trailer"
meta_title: "Tem Trailer - O Marketplace dos Trailers e Motorhomes"
meta_description: "Venha descobrir os melhores trailers e motorhomes do mercado"
meta_image: "motorhome.jpg" # should exist in `app/assets/images/`
